[[server]]
name = "gabelle"
tags = ["pantagruweb", "hetzner"]
[server.config]
address = "https://gabelle.pantagruweb.club:8120"
enabled = true

##

[[stack]]
name = "pantagruweb-n8n"
tags = ["pantagruweb"]
[stack.config]
server = "gabelle"
links = [
  "https://nhuitn.pantagruweb.club"
]
poll_for_updates = true
linked_repo = "pantagruweb-main"
run_directory = "stacks/n8n"
environment = """
GENERIC_TIMEZONE=Europe/Paris
DOMAIN_NAME=pantagruweb.club
SUBDOMAIN=nhuitn
"""

##

[[stack]]
name = "pantagruweb-slskd-dany"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://dany-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-dany"
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=dany
SEED=$(date +%s)
SUBDOMAIN=dany-gargamelle
COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque
echo > seed.env
echo "COOLECTIONS_PATH=${COOLECTIONS_PATH}" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
"""

##

[[stack]]
name = "pantagruweb-slskd-nelly"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://nelly-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-nelly"
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=nelly
SEED=$(date +%s)
SUBDOMAIN=nelly-gargamelle
COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque
echo > seed.env
echo "COOLECTIONS_PATH=${COOLECTIONS_PATH}" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
"""

##

[[stack]]
name = "pantagruweb-slskd-template"
template = true
tags = ["pantagruweb", "slskd", "template"]
[stack.config]
server = "gabelle"
links = [
  "https://SUBDOMAIN.pantagruweb.club"
]
destroy_before_deploy = true
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-<COOLECTION_NAME>"
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTION_NAME=<COOLECTION_NAME>
SEED=$(date +%s)
SUBDOMAIN=<COOLECTION_NAME>-gargamelle
COOLECTIONS_DIR=/mnt/remote/vip/Coolections/Audiothèque
echo > seed.env
echo "COOLECTIONS_DIR=${COOLECTIONS_DIR}" >> seed.env
echo "COOLECTION_NAME=${COOLECTION_NAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTION_NAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTION_NAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
"""

##

[[stack]]
name = "pantagruweb-slskd-tristan"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://tristan-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-tristan"
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=Tristan
SEED=$(date +%s)
SUBDOMAIN=tristan-gargamelle
COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque
echo > seed.env
echo "COOLECTIONS_PATH=${COOLECTIONS_PATH}" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
"""

##

[[repo]]
name = "pantagruweb-main"
tags = ["pantagruweb"]
[repo.config]
server = "gabelle"
builder = "local"
git_account = "trivoallan"
repo = "constructions-incongrues/pantagruweb"

##

[[resource_sync]]
name = "pantagruweb"
tags = ["pantagruweb"]
[resource_sync.config]
linked_repo = "pantagruweb-main"
resource_path = [
  "komodo.toml",
  "stacks/n8n/stack.toml",
  "stacks/slskd-nelly/stack.toml",
  "stacks/slskd-dany/stack.toml",
  "stacks/slskd-tristan/stack.toml",
  "stacks/slskd-template/stack.toml"
]
managed = true
match_tags = ["pantagruweb"]