[[server]]
name = "gabelle"
tags = ["pantagruweb", "hetzner"]
[server.config]
address = "https://gabelle.pantagruweb.club:8120"
enabled = true

[[repo]]
name = "pantagruweb-main"
tags = ["pantagruweb"]
[repo.config]
server = "gabelle"
builder = "local"
git_account = "trivoallan"
repo = "constructions-incongrues/pantagruweb"

##

[[resource_sync]]
name = "pantagruweb"
tags = ["pantagruweb"]
[resource_sync.config]
linked_repo = "pantagruweb-main"
resource_path = [
  "komodo.toml",
  "stacks/n8n/stack.toml",
  "stacks/slskd-nelly/stack.toml",
  "stacks/slskd-dany/stack.toml",
  "stacks/slskd-tristan/stack.toml",
  "stacks/slskd-gakona/stack.toml"
]
managed = false
match_tags = ["pantagruweb"]