services:
  booklore:
    image: booklore/booklore:${BOOKLORE_IMAGE_TAG}
    networks:
      - saltbox
      - default
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      - DATABASE_USERNAME=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.network: saltbox
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-mots.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-mots.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-mots.rule: Host(`mots.pantagruweb.club`)
      traefik.http.services.pantagruweb-mots.loadbalancer.server.port: 6060
    volumes:
      - ./booklore:/app/data
      - ./books:/books

  mariadb:
    image: linuxserver/mariadb:11.4.8
    container_name: booklore_mariadb
    env_file:
      - .env
    volumes:
      - ${MARIADB_CONFIG_PATH}:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  saltbox:
    external: true
