services:
  slskd:
    restart: unless-stopped
    image: slskd/slskd:0.23.2
    user: "${UID-1000}:${GID-1000}"
    networks:
      - saltbox
    env_file: seed.env
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-slskd-nelly.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-slskd-nelly.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-slskd-nelly.rule: Host(`${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-slskd-nelly.loadbalancer.server.port: 5030
    volumes:
      - /mnt/remote/vip/Coolections/Audiothèque/${COOLECTIONS_USERNAME}/downloads/slskd:/data/downloads
      - /etc/localtime:/etc/localtime:roe

networks:
  saltbox:
    external: true
