[[stack]]
name = "pantagruweb-slskd-nelly"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://nelly-gargamelle.pantagruweb.club"
]
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-nelly"
destroy_before_deploy = true
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=nelly
SEED=$(date +%s)
SUBDOMAIN=nelly-gargamelle
COOLECTIONS_PATH=/mnt/remote/vip-audio/Audiothèque
echo > seed.env
echo "COOLECTIONS_PATH=${COOLECTIONS_PATH}" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
"""