[[server]]
name = "gabelle"
tags = ["hetzner", "pantagruweb", "system"]
[server.config]
address = "https://gabelle.pantagruweb.club:8120"
enabled = true

##

[[stack]]
name = "pantagruweb-slskd"
template = true
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://<USERNAME>-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=<USERNAME>
SEED=$(date +%s)
SUBDOMAIN=<USERNAME>-gargamelle
echo > seed.env
echo "COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
file_contents = """
services:
  slskd:
    restart: unless-stopped
    image: slskd/slskd:0.23.2
    user: "${UID-1000}:${GID-1000}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_UMASK=0000
      - SLSKD_FILE_PERMISSION_MODE=644
      - SLSKD_REMOTE_FILE_MANAGEMENT=true
      - SLSKD_SHARED_DIR=/downloads
      - SLSKD_DOWNLOADS_DIR=/downloads
    networks:
      - saltbox
    env_file: seed.env
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-slskd-<USERNAME>.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-slskd-<USERNAME>.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-slskd-<USERNAME>.rule: Host(`${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-slskd-<USERNAME>.loadbalancer.server.port: 5030
    volumes:
      - /mnt/remote/vip/Coolections/Audiothèque/${COOLECTIONS_USERNAME}/__Gargamelle:/downloads
      - /etc/localtime:/etc/localtime:ro

networks:
  saltbox:
    external: true
"""

##

[[stack]]
name = "pantagruweb-slskd-dany"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://dany-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=Dany
SEED=$(date +%s)
SUBDOMAIN=dany-gargamelle
echo > seed.env
echo "COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
file_contents = """
services:
  slskd:
    restart: unless-stopped
    image: slskd/slskd:0.23.2
    user: "${UID-1000}:${GID-1000}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_UMASK=0000
      - SLSKD_FILE_PERMISSION_MODE=644
      - SLSKD_REMOTE_FILE_MANAGEMENT=true
      - SLSKD_SHARED_DIR=/downloads
      - SLSKD_DOWNLOADS_DIR=/downloads
    networks:
      - saltbox
    env_file: seed.env
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-slskd-dany.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-slskd-dany.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-slskd-dany.rule: Host(`${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-slskd-dany.loadbalancer.server.port: 5030
    volumes:
      - "/mnt/remote/vip/Coolections/Audiothèque/Dany mp3-flac/downloads/slskd:/downloads"
      - /etc/localtime:/etc/localtime:ro

networks:
  saltbox:
    external: true
"""

##

[[stack]]
name = "pantagruweb-slskd-nelly"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://nelly-gargamelle.pantagruweb.club"
]
destroy_before_deploy = true
additional_env_files = ["seed.env"]
pre_deploy.command = """
COOLECTIONS_USERNAME=Nelly
SEED=$(date +%s)
SUBDOMAIN=nelly-gargamelle
echo > seed.env
echo "COOLECTIONS_PATH=/mnt/remote/vip/Coolections/Audiothèque" >> seed.env
echo "COOLECTIONS_USERNAME=${COOLECTIONS_USERNAME}" > seed.env
echo "SEED=${SEED}" >> seed.env
echo "SLSKD_SLSK_PASSWORD=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SLSKD_SLSK_USERNAME=Pantagruweb${COOLECTIONS_USERNAME}${SEED}" >> seed.env
echo "SUBDOMAIN=${SUBDOMAIN}" >> seed.env

cat seed.env

echo -n "https://${SUBDOMAIN}.pantagruweb.club"
"""
file_contents = """
services:
  slskd:
    restart: unless-stopped
    image: slskd/slskd:0.23.2
    user: "${UID-1000}:${GID-1000}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_UMASK=0000
      - SLSKD_FILE_PERMISSION_MODE=644
      - SLSKD_REMOTE_FILE_MANAGEMENT=true
      - SLSKD_SHARED_DIR=/downloads
      - SLSKD_DOWNLOADS_DIR=/downloads
    networks:
      - saltbox
    env_file: seed.env
    labels:
      traefik.enable: true
      com.github.saltbox.saltbox_managed: true
      traefik.http.routers.pantagruweb-slskd-nelly.entrypoints: web,websecure
      traefik.http.routers.pantagruweb-slskd-nelly.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker
      traefik.http.routers.pantagruweb-slskd-nelly.rule: Host(`${SUBDOMAIN}.pantagruweb.club`)
      traefik.http.services.pantagruweb-slskd-nelly.loadbalancer.server.port: 5030
    volumes:
      - /mnt/remote/vip/Coolections/Audiothèque/${COOLECTIONS_USERNAME}/__Gargamelle:/downloads
      - /etc/localtime:/etc/localtime:ro

networks:
  saltbox:
    external: true
"""

[[repo]]
name = "pantagruweb-main"
tags = ["pantagruweb"]
[repo.config]
server = "gabelle"
builder = "local"
git_account = "trivoallan"
repo = "constructions-incongrues/pantagruweb"

##

[[resource_sync]]
name = "pantagruweb"
tags = ["pantagruweb"]
[resource_sync.config]
linked_repo = "pantagruweb-main"
resource_path = ["stacks/main.toml"]
managed = true
match_tags = ["pantagruweb"]