[[stack]]
name = "pantagruweb-slskd-{{ cookiecutter.coolection_name | lower }}"
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://{{ cookiecutter.subdomain }}.pantagruweb.club"
]
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-{{ cookiecutter.coolection_name | lower }}"
destroy_before_deploy = false
environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/app/downloads
SLSKD_DOWNLOADS_DIR=/app/downloads
COOLECTION_NAME={{ cookiecutter.coolection_name }}
HASH={{ random_ascii_string(12) }}
SUBDOMAIN={{ cookiecutter.subdomain }}
COOLECTIONS_DIR={{ cookiecutter.coolections_dir }}
"""