[[stack]]
name = "pantagruweb-slskd-bender"
temmlate = true
tags = ["pantagruweb", "slskd"]
[stack.config]
server = "gabelle"
links = [
  "https://bender-gargamelle.pantagruweb.club"
]
linked_repo = "pantagruweb-main"
run_directory = "stacks/slskd-bender"
destroy_before_deploy = true

environment = """
PUID=1000
PGID=1000
TZ=Europe/Paris
SLSKD_REMOTE_CONFIGURATION=true
SLSKD_UMASK=0000
SLSKD_FILE_PERMISSION_MODE=644
SLSKD_REMOTE_FILE_MANAGEMENT=true
SLSKD_SHARED_DIR=/downloads
SLSKD_DOWNLOADS_DIR=/downloads
COOLECTION_NAME=Bender
HASH=ITsfoDcIVsiI
SUBDOMAIN=bender-gargamelle
COOLECTIONS_DIR=/mnt/remote/vip/Coolections/Audiothèque
"""